language: python

cache: pip

# TODO
# Create athe Same Travis with Build Stages, so only deploy if build ok on all jobs
# https://docs.travis-ci.com/user/build-stages/

# Limit under which Conditions we run Travis
branches:
  only:
  - master      # Build if the branch is the master branch
  - development
  - /^v.*$/     # Support building Tags commits on any branch (starting with 'v' in this case).

matrix:
  include:
  - name: "Linux, Python 3.7.5"
    os: linux
    dist: xenial
    python: "3.7.5"
  - name: "Linux, Python 3.8"
    os: linux
    dist: xenial
    python: "3.8"

#  - name: "Windows, Python 3.8 (x64)"
#    os: windows
#    language: sh
#    python: "3.8"
#    before_install: choco install python --version=3.8
#    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
# Check if the Merge Operation is allowed
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then dev/Travis/RunTravisTests.bat; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./dev/Travis/RunTravisTests.sh; fi

- python --version --version
- python -m pip install --upgrade pip setuptools wheel
# don't use the '--upgrade' to not upgrade pinned requirements with generic ones
- pip install -r requirements.txt

# Capture some information
- pip list

before_script:
# Startup Test Server - !!! This might take a bit time, so in script we run linting first to give the startup enough time
#- if [ "$TRAVIS_OS_NAME" = "windows" ]; then dev/run_test_server.bat detached; fi
#- if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./dev/run_test_server.sh detached; fi

#- sleep 15 # Give the server some time to startup before tests are starting, we could also run the tests after Linting for a natural delay but this is ok for now

- if [ "$TRAVIS_OS_NAME" = "linux" ]; then ping -c 4 127.0.0.1; fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then ping -n 4 127.0.0.1; fi

script:
# Run Tests
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then dev/run_tests.bat travis-ci; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./dev/run_tests.sh travis-ci; fi

# Run Linting
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then dev/run_linters.bat; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./dev/run_linters.sh; fi

# Run Package Safety Checks
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then dev/check_package_safety_bare.bat; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./dev/check_package_safety.sh; fi

# Kill the Test Server
#- if [ "$TRAVIS_OS_NAME" = "windows" ]; then dev/kill_test_server.bat; fi

# Kill Python processes - Travis doesn't set the title on Windows
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then tasklist //fi "imagename eq python.exe"; fi
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then taskkill //im python.exe //f; fi


after_success:
- codecov
