# Generated by Django 2.2.5 on 2019-10-05 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='ScrapeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ScrapeType',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('prod_base_url', models.CharField(max_length=250)),
                ('dynamic_page', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricefinderapp.Currency')),
            ],
            options={
                'db_table': 'Store',
            },
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_url', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=30)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricefinderapp.Store')),
            ],
            options={
                'db_table': 'StoreProduct',
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshhold', models.IntegerField()),
                ('store_prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricefinderapp.StoreProduct')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Userproduct',
            },
        ),
        migrations.CreateModel(
            name='UserNewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('DF', 'defined'), ('UD', 'undefined')], default='UD', max_length=2)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserNewsLetter',
            },
        ),
        migrations.CreateModel(
            name='ScrapeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('scrape_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricefinderapp.ScrapeType')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricefinderapp.Store')),
            ],
            options={
                'db_table': 'ScrapeTemplate',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField()),
                ('store_prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricefinderapp.StoreProduct')),
            ],
            options={
                'db_table': 'ProductPrice',
            },
        ),
        migrations.CreateModel(
            name='NewsLetterUserProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_newsletter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricefinderapp.UserNewsLetter')),
                ('user_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricefinderapp.UserProduct')),
            ],
            options={
                'db_table': 'NewsLetterUserProduct',
            },
        ),
        migrations.CreateModel(
            name='NewsLetterTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('MON', 'monday'), ('TUE', 'tuesday'), ('WED', 'wednesday'), ('THR', 'thursday'), ('FRI', 'friday'), ('SAT', 'staturday'), ('SUN', 'sunday')], default='MON', max_length=3)),
                ('time', models.TimeField()),
                ('user_newsletter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricefinderapp.UserNewsLetter')),
            ],
        ),
    ]
