# Generated by Django 2.2.6 on 2019-10-10 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_url', models.TextField(unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshhold', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricefinderapp.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserNewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('prod_base_url', models.TextField(unique=True)),
                ('dynamic_page', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricefinderapp.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xpath', models.TextField(unique=True)),
                ('scrape_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricefinderapp.ScrapeType')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricefinderapp.Store')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricefinderapp.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricefinderapp.Store'),
        ),
        migrations.CreateModel(
            name='NewsLetterUserProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_newsletter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricefinderapp.UserNewsLetter')),
                ('user_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricefinderapp.UserProduct')),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetterTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('MON', 'monday'), ('TUE', 'tuesday'), ('WED', 'wednesday'), ('THR', 'thursday'), ('FRI', 'friday'), ('SAT', 'staturday'), ('SUN', 'sunday')], default='MON', max_length=3)),
                ('time', models.TimeField()),
                ('user_newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricefinderapp.UserNewsLetter')),
            ],
        ),
    ]
