# Generated by Django 2.2.5 on 2019-10-14 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricefinderapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletteruserproduct',
            old_name='user_newsletter_id',
            new_name='user_newsletter',
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='scrapetemplate',
            name='xpath',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='threshhold',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='newsletteruserproduct',
            unique_together={('user_newsletter', 'user_product')},
        ),
        migrations.AlterUniqueTogether(
            name='scrapetemplate',
            unique_together={('store', 'scrape_type')},
        ),
        migrations.AlterUniqueTogether(
            name='usernewsletter',
            unique_together={('user', 'name')},
        ),
    ]
