# Generated by Django 2.2.5 on 2019-10-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricefinderapp', '0002_auto_20191014_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_url',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('store', 'prod_url')},
        ),
    ]
