# Generated by Django 3.0 on 2019-12-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricefinderapp', '0003_auto_20191015_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='error',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('product', 'date_time')},
        ),
    ]
