# Generated by Django 3.0.5 on 2020-05-06 10:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricefinderapp', '0006_auto_20200419_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='error',
        ),
        migrations.AlterField(
            model_name='productprice',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
    ]
